https://archive.org/search?tab=all&query=documentary&sort=-date&and%5B%5D=mediatype%3A%22movies%22
instale tudo o que for necessario
gere um .m3u
instale crawl4ai
preciso dos 50 primeiros videos do autor
teste com ffmpeg para ver se funcionam
